[tool.black]
line-length = 100
target-version = ["py311"]
include = '\.pyi?$'

[tool.ruff]
target-version = "py311"
line-length = 100
select = ["E", "F", "I", "N", "UP", "B", "C4"]
ignore = ["E501"]
fix = true

[tool.pytest.ini_options]
addopts = "-q"
